### ISSUE TITLE
Transclusion

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#132]
Based on a discussion on the mailing list we move this over here for further discussion.

**Comment by michael** [comment]
GJTorikian:

Heya-- 

I made a _very_ similar post about what I am going to propose over at 
the pandoc discussion list. After searching some more for a 
documentation system that fits an itch I must scratch, I was referred 
to Substance. Overall, I'm extremely impressed, but there's one 
feature missing that would make it essential in any documentation 
project. 

Suppose you have a document that consists of several chapters. These 
chapters can either be individual files, or several documents Would it 
be possible to use Substance to refer to reusable text via IDs? By 
playing around in a demo org, I suspect this  is not possible; so I'm 
wondering how hard it would be to implement  the feature myself (or 
ask for an enhancement request). 

Here's what I mean: say I have a file called example1. It has a 
sentence that describes a function, and ends with the following: 

This function prints "Hello, World!" to the console log. 
[#trueResponse: It returns true if the operation was successful.] 

Now, example2 has a description of another function like this: 

This function prints "Goodbye, Universe!" to the console log. 
[#trueResponse~example1.html] 

The [#trueResponse]: example1.html, in the output, would resolve to 
"It returns true if the operation was successful." 

In this manner it would be possible to have reusable text throughout 
the documentation. I'm not suggesting the syntax above; merely 
duplicating the current Markdown style for inline links and expanding 
on it. Obviously there should only be one unique ID in all  the files, 
and that's something that will need to be resolved. But the benefits 
of supporting reusable text should hopefully be apparent.

**Comment by michael** [comment]
Hey!

Yes, that would be possible from a data-structure point of view. All Substance content nodes live in a flat object space and can reference each other. However there are some issues, that need to be cleared up at first:
How should the UI workflow for referencing such shared nodes look like? Since Substance doesn't use markup, I don't want to introduce explicit id's for content nodes. So there needs to be an embedded way to search for documents, scan through content nodes and select them.
Who can edit these shared nodes? Only the original owner, or should the user also be able to adjust his own version? Should cross-editing be possible (editing through the embedding document)?
Versioning: One might either want to dynamically embed the latest version or stick with a specific version (that can't be changed externaly)
However what you're describing here is the concept of transclusion [1], and we want to support it in the long run. However I'd like to ensure that it is not confusing, which much depends on how good our UI implementation is. So feel free to come up with ideas, sketches etc. that we can discuss.

-- Michael

[1] http://en.wikipedia.org/wiki/Transclusion

**Comment by michael** [comment]
Hi Michael-- 

Thanks for the information! I tried to build the project on my own, 
but failed on the CouchDB installation, so my technical knowledge of 
the implementation might be a little (or a lot) off. 

With regards to your questions: one idea might be to introduce a sort 
of a highlighting mechanism for marking content as "to be shared" or 
reusable. As a writer, you would scan a document, find a sentence or 
phrase you want to duplicate, and from the text editor column of 
icons, select a higlighter tool to mark it as "shared." Perhaps you 
could have a complete list of shared phrases in a single document 
listed on the right column; or if that ruins the aesthetic, then to 
introduce a new button the left column which presents a popout of the 
shared nodes. 

Editing through the embedded document should NOT be possible. The 
reason being that an edit to an embedded shared node would reflect 
that change across all the documents using that node. That's probably 
not the intended use. Only the source document should control what the 
contents of the shared node become. With that context, whoever can 
edit the original document can edit its nodes marked as "shared." 

These are just my thoughts; if you need a clearer assessment on UI I 
can mock something up, though I warn you I'm not at all a usability 
engineer or, a designer, in the least. 

All the best-- 
Garen

**Comment by jlank** [comment]
Garen,
  I just came across this thread and have had a similar thought process with respect to the functionality you are talking about.    I think a key factor to think about with 'sharing' or 'reusing' content is how do you indicate a piece of content has been designated as such.  Does this feature exist as an orthogonal layer on top of the document itself, or should it be integrated with substance.. would that fit right?  

Two tools come to mid at the moment that do something similar for the former scenario (layer on top), or "sharing"; first you have [Emphasis](https://github.com/NYTimes/Emphasis) by the NYtimes, which allows you to highlight text on a page and re-share it as highlighted text on the page or an anchor-type jump link.  This could be used in a decoupled way with any third party sharing service.   Second you have something with social built in, like Kindle's [social bookmarking](http://www.pocket-lint.com/news/32870/amazon-kindle-popular-highlights-feature).  These highlights show up inline on the text you are reading. 

For the latter scenario, I see 4 use cases that would arise if you wanted to "reuse" the content within the substance environment to construct new documents or alter existing ones (as clones).  The general use case is you want to reuse one (or more) section(s) of a document(s) to mash up into another document (for a research paper lets say).  

These use cases would cascade as follows (I came up with the labels below):
1. **same-as** - this is an inline reference to a document section (or array of sections).  It is purely dynamic and updates when the source section is updated/edited/deleted with a link back indicating it has a parent/source elsewhere.  Let's say it points to the sections 'head'.
2. **clone-snapshot** - this would be the same as scenario 1, except the content does not update, it has a reference to a specific version of that section with a link back.  You would indicate this 'state' upon copy/reuse action.
3. **fork** - this scenario would arise if at any point you became an editor/enhancer on a section obtained via scenario 1 or 2, and altered the content of a section.  For scenario 1 the head reference would break and stay on the current state of a section, and this "new" section would have it's own id/_rev.  
4. **slice** - this last one is somewhat of a hybrid between sharing and reuse.  Say you identify 2 sentences out of a paragraph that you want to stand on it's own for sharing on social media, or inclusion in your own report.  This section would then get it's own id/_rev and reference to a parent item.  Since this item already has it's own id/_rev, if scenario 3 arose where you then edited the section, the reference to the parent would then break and stay on the current state of said parent section.  This designated new section would then have to stand independent of the current document, somewhere, lest it violate the 3 level deep structure limitation currently in place.  Maybe this would then become something like a facet of the document?  Perhaps a 'highlight' section, ranked by some share criteria?  Who knows... this is where things get freaky because although it comes out of a document's context, it obtains a new user defined (undefined?) context based on some other significance to the user, not the original author.  It's like the living dead or a hanging chad.

As far as the UI goes, for sharing perhaps an icon under the comment icon would suffice to link to a section?

These are my thoughts on the issue, I just joined the google group and haven't had a chance to read the other posts, so I hope none of my points were redundant.  Looking to get my feet wet with substance in the near future, I think it is a really cool project.

-John
