### ISSUE TITLE
For RTL languages use a better font

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#183]
Sans, ...

**Comment by akhayyat** [comment]
For the Arabic language, Sans does not look good in Firefox on Linux. Serif or Arial are better, but still not ideal for an otherwise good looking tool. On Windows, "Traditional Arabic" is available and looks good, so it can be the first font in a font stack.

Other options:
- Amiri: Used to be used by a prolific early twentieth century press: http://www.amirifont.org/. Available as a Debian package (fonts-hosny-amiri). My vote goes for this one. A high-quality, beautiful font.
- Scheherazade: Available from: http://scripts.sil.org/ArabicFonts. Also available as a Debian package (fonts-sil-scheherazade).
- Uthman: Available at: http://fonts.qurancomplex.gov.sa/?page_id=608. The site seems to be available only in Arabic at this time. The most recent version of the font can be downloaded using the first download link (currently: http://fonts.qurancomplex.gov.sa/download/UthmanTN1_Ver09.zip). See http://fonts.qurancomplex.gov.sa/?page_id=604 for a sample. The license is stated in Arabic at http://fonts.qurancomplex.gov.sa/?page_id=606. It states that the font "is available for copying, distribution, and use free of charge for personal and commercial purposes, government and private works, publishing, media, and Internet sites in the Kingdom of Saudi Arabia and outside, provided that the font is not attributed to an entity besides the owner of its rights. The Complex reserves all rights of ownership, reproduction and no one or entity is allowed to reprogram it, modify it or modify any part of it in any way or for any reason, or sell it for any reason."

Either of these options is _much_ better than the default system font (e.g. Serif).

**Comment by michael** [comment]
Thanks for your suggestions. We need to delay this a bit. I plan including it in 0.4.2.

**Comment by michael** [comment]
We'll no longer address issues related to the 0.4.0 series. We're pushing hard on 0.5.0 featuring the all-new architecture.

Track progress here: https://github.com/substance/substance/tree/0.5.0

-- we wanna bring in RTL support again, but first stuff need to get stable.
