### ISSUE TITLE
mouse cursors to indicate which text can be edited

### ISSUE THREAD

**Issue by johannesjh** [substance/substance-legacy#25]
i suggest changing the mouse cursor to indicate what can be edited.

(when i tried the writer demo, i did not know which text was meant as label (and thus could not be edited), as opposed to content (that can be edited). )

**Comment by michael** [comment]
Now that's a good idea. What kind of cursor would you use for that? Actually, the cursor isn't wrong (selection-cursor that you would expect in a editor). However you can't visually distinguish between editable areas and labels. 

In this regard, what also needs to be done is displaying placeholders for empty text fields, otherwise you wouldn't be aware there's something that can be edited.

**Comment by michael** [comment]
I was trying to use a different cursor for editable content. But somehow it feels awkward. Now for the first version I added native tooltips that indicate that the text can be edited. 

E.g. "Click to edit Section Name".

I assign this ticket to 0.2, where I can come up with a better solution.

**Comment by michael** [comment]
With the latest UI updates I think this should be clear now.
