### ISSUE TITLE
Context menu: "Idea", "Question", "Error" are mutually exclusive. 

### ISSUE THREAD

**Issue by obuchtala** [substance/substance-legacy#287]
Would be nice to be able to comment a sentence/word with an idea AND a Question.
E.g. User 1 writes a question, User 2 Comments, User 3 comments, User4 writes an Idea, User 1 comments, User 2 writes an error, ... All can be displayed as annotated comments on the comment panel. 
Will be pretty colourful, but this could provide an easy navigation if there is a large list of comments. E.g. "where was that IDEA on this sentence?"

**Comment by michael** [comment]
I was carefully thinking through those options when I implemented mutual exclusion. For me it was important to always prevent from overlapping annotations as it's really hard to display and edit otherwise. As of now you can start with a question annotation and turn that same annotation into an "idea" later. Comments will be preserved when doing that.
