### ISSUE TITLE
What do do about pending changes?

### ISSUE THREAD

**Issue by michael** [substance/substance-legacy#293]
When users are editing text / adding annotations etc. those changes are not stored immediately. A delta will be computed when the current text node losses focus (e.g. you click somewhere else or select a different content element).

Problem: When the user closes the Composer or reloads the page (cmd+r) those pending changes are lost.

Solution? We should somehow track that there are pending changes and place a hook before:quit or before:reload to make sure those changes are stored.

Other ideas?

**Comment by vectorsize** [comment]
Yes I've been thinking about this lately...
I once read a post about throttling/debouncing that had examples with text, and they where only updating each new word instead of each character ( can't find it anymore ), I think we should have an "autosave" function using such technique. I've found [this post](http://benalman.com/projects/jquery-throttle-debounce-plugin/) I showed you this post at quasipartikel when looking at optimizations.

…And I guess each node type would be responsible of notifying the composer on when to save?

**Comment by yuchi** [comment]
Shouldn't it be as easy as `$el.on('change keypress paste', _.debounce(_.bind(this.onChange, this), 400))`?

**Comment by michael** [comment]
We could do that. However the idea was to collect all changes while editing text until they are confirmed (committed). So we have less operations to be stored. However, we can just maintain a dirty state and prevent the app from being closed / or reloaded until all pending changes have been applied.
