### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by calas** [substance/substance-legacy#3]
One evil user can insert javascript code into a document: 

Take a look at http://substance.quasipartikel.at/#load/d80d05de77c82af928c743214da792fd

**Comment by michael** [comment]
Ah thanks for bringing this up! Escaping HTML is something I'm likely to forget. Will fix this asap.

**Comment by michael** [comment]
Just found out that this problem no longer exists at the current version living in the master branch, as I switched to inline editing using contenteditable="true", which does escape all characters by default. I'll need another day or two before I can update the demo page.

**Comment by calas** [comment]
Then you loose all markup? I think that some markup would be desirable, for example for bold, emphasys, lists, etc. I'm not using the project though, I'm just curious. It looks, really nice, hope someday will find a use for it ;)

**Comment by michael** [comment]
I'll support a restricted set of semantical markup (em, strong, lists, links) through document.execCommand. However, I need to dig in deeper into HTML5 backed rich-text editing. I think I'll no longer use markdown because having this restricted set of semantic HTML tags (easily parsable) suffices for our case. And everything will be a bit faster then. -> I no longer need local re-renderings on node-content changes, which slowed things down, esp. when you were typing fast.
