### ISSUE TITLE
Why (and where) is all the code gone?

### ISSUE THREAD

**Issue by jondo** [substance/substance-legacy#348]

**Comment by obuchtala** [comment]
The old substance platform is not under development anymore.
We have rewritten everything and are developing this idea in the scope of a native application rather than a platform.

@michael is the old source code still available?
But I doubt that it is still useful, as it has not been touched since over a year.

**Comment by jondo** [comment]
Ah, I see. I do not need the old code, thank you. Where is the code of the rewrite?

**Comment by michael** [comment]
It's spread across many repositories. We haven't had to document everything properly.

Not all pieces are open sourced yet. The editor (which is a very custom integration of the whole stack). It's source code won't be available for the time being. But our plan is to release editing components that can be integrated individually, once our API's stabilized.

However.. consider the modules `data`, `operator`, `article`, and many more stable and open.

We'll are working on dev documentation on the side. See current progress here: http://code.substance.io

**Comment by jondo** [comment]
I have also found [a corresponding mailing list thread](https://groups.google.com/forum/#!topic/substance_/gcFmD4GtzUw).
