### ISSUE TITLE
Better semantics

### ISSUE THREAD

**Issue by lhunath** [substance/substance-legacy#349]
Ever since HTML 4, there is the general consensus that when writing documents, semantics are more important than style.  We no longer mark up our content with font tags, italics and bold.  We use tags that convey the semantics of our elements and then apply style to convey those semantics.

Substance should not regress on that front.  There should be no italics or bold buttons.  sub and sup are dubious.  At the same time, we need to gain a wealth of semantic-specific buttons.  We need buttons for `<em>`, `<strong>`, `<dfn>`, `<kbd>`, `<var>`, `<q>`, etc (see https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content).

That way, I can write proper documents, where there is a difference between code, sample text and keyboard input, definitions and emphasis, quotations and citations.  As there should be.

**Comment by michael** [comment]
Thanks for your input. We are very serious about separating semantics from presentation (style). Internally we use semantic types (strong, emphasis) . The **B** and _I_ buttons are only there because there's no known visual mark for a thing like "strong emphasis" that could replace it.

How would you handle sub and superscript scenarios.. e.g. people use it for simple math constructs like x^2...  For our scientific version of the editor we'll just work with a formula type, making the sub/sup obsolete.

**Comment by lhunath** [comment]
I'd advise against B and I on the strong and emphasis buttons, since that's merely one possible rendering of them; and it adds to the confusion/ambiguity between italics and emphasis.  In my personal opinion, a button with an "em" on it in italics is acceptable.

sub/sup is probably OK to keep around, though it probably shouldn't be more prominent than the other semantics and live somewhere near math, var, meter, etc.  I don't know how you'll make all of these semantics prominent and not clutter the interface with them, perhaps a pop-out and the ability to pick three or so that show on the bar.  I'm sure you're better at solving that problem than I could be.
