### ISSUE TITLE
Better extension concept.

### ISSUE THREAD

**Issue by obuchtala** [substance/substance-legacy#357]
For example looking at this:
https://github.com/substance/substance/blob/next/src/article/nodes/index.js

I don't think it is the right place to have the initialize method there. Particularly thinking of it as an extension internally is overly complicated.

Similar here: https://github.com/substance/substance/blob/next/src/article/article.js#L18
There is application extension framework in core library context, which does not look very good.

As rule I would say, if Writer introduces the concept of extensions, then it should provide core extensions...

**Comment by michael** [comment]
This is not core-library stuff. It's more just a reference implementation of general-purpose substance document (markdown features). It is not in the scope of the writer extension mechanism. I thought that substance document implementations don't need an extension mechanism for now since you always start from zero anyway.

However maybe substance article should live outside of the substance repo and instead we just make a nodes folder so different projects can import commonly used node definitions for their specific document type. I agree this is smelly as it is right now. Let's discuss this soon! And then I will put things into the right places.

**Comment by obuchtala** [comment]
What I am talking about is for instance Article.CoreModule which seems to go into the writer somewhere... and this mechanism is rather intransparent.
Every article should be a leaf implementation and node sharing is problematic IMO considering our experiences.

**Comment by michael** [comment]
Agreed. There should not be such a thing as Article.CoreModule. The writer is not affected though.. we used this for the Interview document type. Will clean that up.

**Comment by obuchtala** [comment]
No hurry... just collecting things we need to address before release.

**Comment by michael** [comment]
Done.
