### ISSUE TITLE
Text section with whole text set to 'code' format receives a border

### ISSUE THREAD

**Issue by obuchtala** [substance/substance-legacy#54]
Process: 
- create a section
- add text node
- write some text
- mark the whole text
- set to 'code' format

Effect: text node becomes bordered. This can not be undone.

find a document 'Issue 54' about this

**Comment by michael** [comment]
This is due to peculiarities of the contenteditable functionality that browsers provide, since it doesn't support custom tags. Using code is such a custom tag (unlike `<b>`, `<i>`, `<a>` which are sopported natively), which causes issues. I'll put some efforts into Proper (http://github.com/michael/proper) to overcome this in the long run.

**Comment by michael** [comment]
The main problem here is that you can't toggle `<code>` areas on and off. Because there's no command for it.

**Comment by obuchtala** [comment]
ok, border is 'code', but one can not deactivate

**Comment by obuchtala** [comment]
Code-Trap: if code reaches to the end of text node, one can not create normal text after code block.

**Comment by michael** [comment]
This will be resolved along with a major update for the Richtext Editor. We'll implement our own layouting engine to ensure semantically correct markup.
