### ISSUE TITLE
Opera is supported

### ISSUE THREAD

**Issue by Poetro** [substance/substance-legacy#69]
The check for supported browsers is pretty dumb. The viewing of pages works really well in Opera, and even if it is not, the application shouldn't force one to download another browser, just indicate that there might be errors and glitches in that browser, for example how Google does on say Picassa.

**Comment by michael** [comment]
Thanks. We are aware of that. However, at this early stage it was easier to limit the range of supported browsers and thus, reduce testing efforts.

You can expect Opera Support for the next release (0.2.0, which should be ready in a couple of weeks). For searching/reading documents all major browsers will be supported in future. Because of diverging behavior of the contenteditable attribute among browers, writing documents will remain limited to Webkit-based browers.
