### ISSUE TITLE
Feature request - Cross References

### ISSUE THREAD

**Issue by maacl** [substance/substance-legacy#94]
Numbered cross references would be hugely useful especially if they could autoupdate if a section is moved around.

**Comment by michael** [comment]
Yes we're planning to add that (along with cross-document references/citations). But before we can do that, the PROPER Rich Text Editor needs to be rewritten so it can offer more control about inline text. We're in the process of acquiring some public funding to back up development. Turns out this will be a bigger project.

**Comment by maacl** [comment]
Sounds great. Is there any detailed documentation for the internal
json format substance.io is using?

/mac

On Mon, Jul 18, 2011 at 4:08 PM, michael
reply@reply.github.com
wrote:

**Comment by michael** [comment]
The internal format is an application of a Data.js Data.Graph.

Here's more http://substance.io/#substance/substance-internals/_section_b656a66ee93d0d6f4a64bfe38a92eb84

And http://substance.io/#michael/data-js

Reading through that tutorial could also help. http://substance.io/#substance/substance-as-a-blog-engine

**Comment by nichtich** [comment]
Please have a look at the [Pandoc](johnmacfarlane.net/pandoc/) document model which includes citations and references among other features. Pandoc also has an internal format which is translated to different forms of markup.

**Comment by michael** [comment]
Yeah I'm aware of this. However, we're redesigning the current document model from scratch.. Please put your suggestions here: http://github.com/substance/document
